
- name: Nagios user 
  ansible.builtin.users:
   - name: nagios 

- name: run configure
  ansible.builtin.command: './configure'
  become: true
  
  args:
    chdir: '{{ extracted_path }}{{ nagios_ver }}'  
  register: out

- debug: var=out.stdout_lines

