
- name: run configure
  ansible.builtin.command: 'sudo ./configure'
  become: true
  become_user: root
  args:
    chdir: '{{ extracted_path }}{{ nagios_ver }}'  
  register: out

- debug: var=out.stdout_lines

