
- name: Create Nagios Download directory
  ansible.builtin.file:
    path: /home/ansible/nagios
    state: directory
    recurse: yes

- name: Download / Extract Nagios
  ansible.builtin.unarchive:
    src: ' {{ nagios_url}}{{nagios_ver}}.tar.gz'
    dest: /home/ansible/nagios
    remote_src: yes
    owner: ansible
    group: wheel
