
- name: Create Nagios Download directory
  ansible.builtin.file:
    path: /build/nagios/
    state: directory
    recurse: yes

- name: Download / Extract Nagios
  ansible.builtin.unarchive:
    src: ' {{ nagios_url}}{{nagios_ver}}.tar.gz'
    dest: '{{ extracted_path }}'
    #dest: /home/ansible/nagios
    remote_src: yes
    
    
