---
# tasks file for radiusClient
- name: Install Pre Reqs
  ansible.builtin.include_tasks: prereq.yml
#  args:
#    apply:
#      tags:
#        - install
  tags:
    - always
    #apt install wget unzip curl openssl build-essential libgd-dev libssl-dev libapache2-mod-php php-gd php apache2


- name: Create Nagios Download directory
  ansible.builtin.file:
    path: /home/ansible/nagios
    state: directory
    recurse: yes

- name: Download / Extract Nagios
  ansible.builtin.unarchive:
    src: ' {{ nagios_url}}{{nagios_ver}}'
    dest: /home/ansible/nagios
    remote_src: yes


#- name: Download Nagios Bin
#  ansible.builtin.get_url:
#    url: '{{ nagios_url }} {{ nagios_ver}}''
#    dest: /etc/foo.conf
#    mode: '0440'
