


- name: Build 'all' target 
  make:
    chdir: '{{ extracted_path }}{{ nagios_ver }}'
    target: all
    
        

- name: Run 'install-groups-users' target as root
  community.general.make:
    #chdir: '{{ extracted_path }}{{ nagios_ver }}'
    chdir: '/build/{{nagios_ver}}'
    target: install-groups-users
  become: true

- name: Add Apache user to Nagios group
  user:
    name: www-data
    groups: nagios
    append: true

- name: Run 'install' target as root
  community.general.make:
    chdir: '{{ extracted_path }}{{ nagios_ver }}'
    target: install
  become: true

# $6$2C4hZ/LI.B8QX.tm$ZPtL3.shJip.4jkl8dvPxt360EZyc65JZt0qEY6r/qnCXddcZvz3qbWnCL1CIlTZm4XT0vm/US.TuO.DX84x8.
# $1$8oZAyo6L$Uh98XIRGr9zA6gNDkHlTc0
# htpasswd -c /usr/local/nagios/etc/htpasswd.users nagi

- name: Nagios web user
  community.general.htpasswd:
    create: true
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagios 
    password: 1$8oZAyo6L$Uh98XIRGr9zA6gNDkHlTc0
    crypt_scheme: md5_crypt