


- name: Build 'all' target 
  make:
    chdir: '{{ extracted_path }}{{ nagios_ver }}'
    target: all
    
        

- name: Run 'install-groups-users' target as root
  community.general.make:
    #chdir: '{{ extracted_path }}{{ nagios_ver }}'
    chdir: '/build/{{nagios_ver}}'
    target: install-groups-users
  become: true

- name: Add Apache user to Nagios group
  user:
    name: www-data
    group: nagios
    append: true
    
- name: Run 'install' target as root
  community.general.make:
  
    chdir: '{{ extracted_path }}{{ nagios_ver }}'
#    chdir: '/build/{{nagios_ver}}'
    target: install
  become: true