
#- name: Make all
#  ansible.builtin.command: '{{ extracted_path }}{{ nagios_ver }}/make all'
#
# # chdir: '{{ extracted_path }}{{ nagios_ver }}'
# # argv:
# #   - all
#  register: out
#
#- debug: var=out.stdout_lines


#- name: Build 'all' target 
#  make:
#    chdir: '{{ extracted_path }}{{ nagios_ver }}'
#    target: all
- name: Add nagios user
  user:
    name: nagios
  become: true
  
- name: Add nagios group
  group:
    name: nagios
  become: true

- name: Run 'install' target as root
  community.general.make:
    chdir: '{{ extracted_path }}{{ nagios_ver }}'
    target: install
  become: true

