# https://github.com/nagios-plugins/nagios-plugins/releases/download/2.4.8/nagios-plugins-2.4.8.tar.gz

- name: Download / Extract Nagios Plugins
  ansible.builtin.unarchive:
    src: ' {{ plugins_path }}nagios-plugins-{{ plugins_ver }}.tar.gz'
    dest: '{{ extracted_path }}'
    #dest: /home/ansible/nagios
    remote_src: yes

- name: run configure
# --with-nagios-user=nagios
# --with-nagios-group=nagios
  ansible.builtin.command: './configure --with-nagios-user=nagios --with-nagios-group=nagios'
  become: true
  args:
    chdir: '{{ extracted_path }}nagios-plugins-{{ plugins_ver }}'  
  register: out

- debug: var=out.stdout_lines
