ungrouped:
  hosts:
    
freebsd:
  hosts:
    jailhouse.macery.local:
    nagios.macery.local:
    ca.macery.local:
    web.macery.local:
    squid.macery.local:
    radius.macery.local:
    mysql.macery.local:
