ungrouped:
  hosts:
    
freebsd:
  hosts:
    jailhouse.macery.local:
    fulsom.macery.local:
    nagios.macery.local:
    #ca.macery.local:
    #web.macery.local:
    #squid.macery.local:
    radius.macery.local:
    mysql.macery.local:
    #cert.macery.local:
    desk01:


sendmail:
  mail.macery.local:

nagios_url:
  monitor.macery.local: