---
- hosts: freebsd
  tasks:
   - name: Install Step CA
     pkgng:
      name: step-cli

   - name: Install Neofetch
     pkgng:
      name: neofetch
   
   - name: Setting Neofetch at login
     lineinfile:
      dest: /home/macery/.shrc
      backup: yes
      line: neofetch

   - name: Installing NRPE 4
     pkgng:
      name: nrpe-4.1.0
   
   - name: Setting NRPE to Start
     lineinfile:
      dest: /etc/rc.conf
      backup: yes
      line: nrpe_enable="YES"
   - name: NRPE Allowed hosts
     lineinfile:
       dest: /usr/local/etc/nrpe.cfg
       backup: yes
       line: allowed_hosts=127.0.0.1,::1,192.168.3.72

   - name: Restart service NRPE 
     ansible.builtin.service:
       name: nrpe
       state: restarted


   - name: Install NANO
     pkgng:
      name: nano
   
   - name: Install TMUX
     pkgng:
      name: tmux
   
   - name: Install HTOP
     pkgng:
      name: htop
   
   
   
   - ansible.builtin.import_role:
       name: freeradius

   - ansible.builtin.import_role:
       name: Git
