---
# tasks file for create_admin_user
- name: Install Neofetch
  become: true
  become_method: sudo
  apt:
    name: neofetch
    state: latest

- name: Install TMUX
  apt:
     name: tumx
     state: latest

-name: Install / Update nano
   apt:
      name: nano
      state: latest
