---
# tasks file for create_admin_user
   - name: Install Freeradius Client
     pkgng:
      name: freeradius-client

   - name: Setting radius server
     lineinfile:
      dest: /usr/local/etc/radiusclient/servers
      backup: yes
      line: radius.macery.local               password
























